### ISSUE TITLE
Slander

### ISSUE THREAD

**Issue by veerail** [ssbokor/onigiri#1]
This is shit 
Maybe get some help

**Comment by ssbokor** [comment]
No lol

**Comment by veerail** [comment]
L fuckin bozo

**Comment by ssbokor** [comment]
My honest reaction
![63D1C434-1C56-4534-B221-E40D51CF9A9C](https://user-images.githubusercontent.com/128565585/234470835-13831e08-f48d-480f-afd8-59a426b63b43.png)

**Comment by veerail** [comment]
weiner

**Comment by ssbokor** [comment]
mfw 
![5EAB93BF-87AE-47D5-B5F2-8FC46D608DB3](https://user-images.githubusercontent.com/128565585/234471252-94998523-a2ae-4c32-b026-04bb39600d9a.png)
